# Generated by Django 4.0.3 on 2022-06-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanprofile', '0003_humanhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humanhistory',
            old_name='company_name',
            new_name='company',
        ),
    ]
