# Generated by Django 4.0.3 on 2022-06-05 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatroomState',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='room_id')),
                ('state', models.PositiveSmallIntegerField(default=1, help_text='0:拒否,1:待ち,2:許可', verbose_name='承認ステータス')),
                ('society_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society', to=settings.AUTH_USER_MODEL, verbose_name='society')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studnet', to=settings.AUTH_USER_MODEL, verbose_name='studnet')),
            ],
        ),
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='chattext')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroomstate', verbose_name='room_id')),
            ],
        ),
    ]
