# Generated by Django 4.0.3 on 2022-06-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='student_or_society',
            field=models.BooleanField(default=False, help_text='社会人か就活生か'),
        ),
    ]
